
server {
    listen 80;

    #  SockJS WebSocket for /university/ (university portal)
    location ~* ^/university/ {
        proxy_pass https://supervision-service.onrender.com;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host supervision-service.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # ✅ SockJS WebSocket for /student/
    location ~* ^/student/ {
        proxy_pass https://supervision-service.onrender.com;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host supervision-service.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # API proxies
    location /api/auth/ {
        proxy_pass https://auth-service-jjyt.onrender.com;
        proxy_set_header Host auth-service.onrender.com;
        proxy_ssl_server_name on;
    }

    location /api/supervision/ {
        proxy_pass https://supervision-service.onrender.com;
        proxy_set_header Host supervision-service.onrender.com;
        proxy_ssl_server_name on;
    }

    location /api/notification/ {
        proxy_pass https://notification-service-c4re.onrender.com;
        proxy_set_header Host notification-service.onrender.com;
        proxy_ssl_server_name on;
    }

    location /api/reporting/ {
        proxy_pass https://reporting-service-cgd1.onrender.com;
        proxy_set_header Host reporting-service-cgd1.onrender.com;
        proxy_ssl_server_name on;
    }

    location /api/integration/ {
        proxy_pass https://integration-service-d1qx.onrender.com;
        proxy_set_header Host integration-service.onrender.com;
        proxy_ssl_server_name on;
    }
    location /ws/ {
    proxy_pass https://notification-service-c4re.onrender.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_ssl_server_name on;
}

    # React app — must be LAST
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}
