FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /app
COPY pom.xml ./pom.xml
COPY reporting-service/pom.xml ./reporting-service/pom.xml
COPY reporting-service/src ./reporting-service/src
RUN apk add --no-cache maven
RUN mvn clean package -DskipTests -pl reporting-service

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/reporting-service/target/reporting-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]