FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /app
COPY pom.xml ./pom.xml
COPY integration-service/pom.xml ./integration-service/pom.xml
COPY integration-service/src ./integration-service/src
RUN apk add --no-cache maven
RUN mvn clean package -DskipTests -pl integration-service

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/integration-service/target/integration-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "app.jar"]