FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /app
COPY pom.xml ./pom.xml
COPY supervision-service/pom.xml ./supervision-service/pom.xml
COPY supervision-service/src ./supervision-service/src
RUN apk add --no-cache maven
RUN mvn clean package -DskipTests -pl supervision-service

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/supervision-service/target/supervision-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]