server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-fyp-zjubair2122-b5be.g.aivencloud.com:19495/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_rMx8OiH57fa-wUxfO6J}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health

security.jwt.secret=change-me-change-me-change-me-change-me-change-me

